# Generated by Django 3.0.7 on 2020-08-27 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('length', models.CharField(max_length=10)),
                ('width', models.CharField(max_length=10)),
                ('height', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=20)),
                ('purpose', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
