# Generated by Django 3.0.7 on 2020-09-07 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0003_auto_20200907_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
